mydog:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 200  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HAA
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_HFE
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_KFE
    pid: {p: 400.0, i: 0.0, d: 3.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HAA
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_HFE
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: LH_KFE
    pid: {p: 400.0, i: 0.0, d: 3.0}

  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HAA
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_HFE
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_KFE
    pid: {p: 400.0, i: 0.0, d: 3.0}

  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HAA
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_HFE
    pid: {p: 400.0, i: 0.0, d: 3.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: RH_KFE
    pid: {p: 400.0, i: 0.0, d: 3.0}


# Torque Controllers ---------------------------------------
  joint1_torque_controller:
    type: effort_controllers/JointEffortController
    joint: LF_HAA
  joint2_torque_controller:
    type: effort_controllers/JointEffortController
    joint: LF_HFE
  joint3_torque_controller:
    type: effort_controllers/JointEffortController
    joint: LF_KFE

  joint4_torque_controller:
    type: effort_controllers/JointEffortController
    joint: LH_HAA
  joint5_torque_controller:
    type: effort_controllers/JointEffortController
    joint: LH_HFE
  joint6_torque_controller:
    type: effort_controllers/JointEffortController
    joint: LH_KFE

  joint7_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RF_HAA
  joint8_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RF_HFE
  joint9_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RF_KFE

  joint10_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RH_HAA
  joint11_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RH_HFE
  joint12_torque_controller:
    type: effort_controllers/JointEffortController
    joint: RH_KFE

mydog_control_sim_ros:
  linearX: 1
  linearY: 0
  x_scale: 1.0
  y_scale: 1.0
#  stepHeight: 0.12   #foot swing height
#  swingPeriod: 0.2  #trotting gait cycle
