#!/usr/bin/env python3
 
import sys
 
from rqt_robot_gui.robot_gui import RobotPlugin
from rqt_gui.main import Main
 
plugin = 'rqt_robot_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
