#!/usr/bin/env python3
 
import sys
 
from rqt_dog_gui.dog_gui import DogPlugin
from rqt_gui.main import Main
 
plugin = 'rqt_dog_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
